spring:
 datasource:
  username: root
  password: Bikki@123
  url: jdbc:mysql://localhost:3306/bikki
  driver-class-name: com.mysql.jdbc.Driver
 jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
 